// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIAM7_IDI6hz6KOiB_0TA0HEuk08X3wjE',
    appId: '1:1009715520263:web:a5e98cfc0a1cafd1589ba2',
    messagingSenderId: '1009715520263',
    projectId: 'chatapp-60fd6',
    authDomain: 'chatapp-60fd6.firebaseapp.com',
    storageBucket: 'chatapp-60fd6.appspot.com',
    measurementId: 'G-0F0WGXH9TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxWJla0fSYVRbdh5gmb6efNM_HP0tI6_U',
    appId: '1:1009715520263:android:ce01aadef39beba7589ba2',
    messagingSenderId: '1009715520263',
    projectId: 'chatapp-60fd6',
    storageBucket: 'chatapp-60fd6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7kFBlsJd_cFATcip9izkCTvc1Z9d4ihY',
    appId: '1:1009715520263:ios:a028e4c9ed793b52589ba2',
    messagingSenderId: '1009715520263',
    projectId: 'chatapp-60fd6',
    storageBucket: 'chatapp-60fd6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7kFBlsJd_cFATcip9izkCTvc1Z9d4ihY',
    appId: '1:1009715520263:ios:a028e4c9ed793b52589ba2',
    messagingSenderId: '1009715520263',
    projectId: 'chatapp-60fd6',
    storageBucket: 'chatapp-60fd6.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIAM7_IDI6hz6KOiB_0TA0HEuk08X3wjE',
    appId: '1:1009715520263:web:ea29f17e8590d05e589ba2',
    messagingSenderId: '1009715520263',
    projectId: 'chatapp-60fd6',
    authDomain: 'chatapp-60fd6.firebaseapp.com',
    storageBucket: 'chatapp-60fd6.appspot.com',
    measurementId: 'G-4DZ8VFL2QK',
  );
}
